create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  building integer not null default 1,
  floor integer not null check (floor between 1 and 4),
  room integer not null,
  is_active boolean not null default true,
  unique(building, floor, room)
);

create table if not exists public.sightings (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  reporter_user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  status text not null default 'active' check (status in ('active', 'expired', 'flagged'))
);

create table if not exists public.sighting_votes (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  vote_type text not null check (vote_type in ('confirm', 'reject', 'left')),
  created_at timestamptz not null default now(),
  unique(location_id, user_id)
);

create index if not exists sightings_active_idx on public.sightings(status, expires_at, created_at desc);
create index if not exists sightings_location_idx on public.sightings(location_id);
